FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ApiCursos.csproj", "./"]
RUN dotnet restore "./ApiCursos.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "ApiCursos.csproj" -c Release -o /app/build
RUN dotnet publish "ApiCursos.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ApiCursos.dll"]
